In [3]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-dba285d182559f8ab3a83fc56de1ca41f830207404b14aa62343d706d5c61b31"

payload = {
    "input": "my name is sudhanshu",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

print(response.json())


{'object': 'list', 'data': [{'object': 'embedding', 'embedding': [-0.006452379, -0.026823461, -0.028528733, -0.009033331, -0.06539947, -0.019057563, -0.017767087, 0.056734845, -0.004882492, -0.066736035, 0.029150926, -0.050651174, -0.017709475, -0.035925925, 0.03458936, 0.009955099, -0.018366236, -0.028413512, -0.00082671107, 0.029542677, 0.01888473, 0.04334616, 0.040696077, -0.009442365, 0.02972703, -0.030026605, 0.013930225, -0.021385027, 0.02336683, -0.06470814, -0.0113377515, -0.019841066, 0.008002102, 0.02802176, -0.007460563, -0.019253438, -0.0013941748, -0.010191302, -0.0073856693, -0.01717946, -0.012397785, -0.033851944, 0.049545053, -0.0020725387, -0.036156368, -0.022779202, -0.06710474, 0.028805263, -0.023781626, -0.03147839, -0.0131352, 0.011959945, 0.012167343, 0.058854915, 0.047655426, -0.012455395, 0.029427458, 0.058209676, 0.011481778, -0.02829829, -0.018308625, -0.019725844, 0.042954408, 0.03534982, -0.022203097, 0.009425082, 0.008958437, -0.024611216, -0.014103057, -0.

In [2]:
pip install requests

  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
  Using cached urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)

   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
result = response.json()

In [9]:
len(result['data'][0]['embedding'])

1536

In [11]:
a = result['data'][0]['embedding']

In [13]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-dba285d182559f8ab3a83fc56de1ca41f830207404b14aa62343d706d5c61b31"

payload = {
    "input": "sudhanshu use to work for euron",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
b = response.json()['data'][0]['embedding']

In [15]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-dba285d182559f8ab3a83fc56de1ca41f830207404b14aa62343d706d5c61b31"

payload = {
    "input": "rakesh a gen ai batch student",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
c = response.json()['data'][0]['embedding']


In [ ]:
a,b,c

In [16]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-dba285d182559f8ab3a83fc56de1ca41f830207404b14aa62343d706d5c61b31"

payload = {
    "input": "what sudhanshu does",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
inp = response.json()['data'][0]['embedding']


In [19]:
import numpy as np

In [18]:
pip install numpy

   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   ---------------------------------------- 13.1/13.1 MB 82.2 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [21]:
type(a)

list

In [22]:
a = np.array(a)
b= np.array(b)
c = np.array(c)
inp = np.array(inp)

In [24]:
a,b,c,inp

(array([-0.00645238, -0.02682346, -0.02852873, ..., -0.00969585,
         0.01474829, -0.00714371], shape=(1536,)),
 array([-0.0461162 , -0.00981342,  0.05917026, ...,  0.00189482,
         0.00919579, -0.01663782], shape=(1536,)),
 array([-0.00416988, -0.03700995,  0.05361585, ..., -0.03120966,
         0.05270311, -0.01773945], shape=(1536,)),
 array([-0.03277422,  0.00336288,  0.05129212, ..., -0.00561822,
        -0.00875308,  0.00986446], shape=(1536,)))

In [26]:
dist_inp_a = np.linalg.norm(inp-a)
dist_inp_b = np.linalg.norm(inp-b)
dist_inp_c = np.linalg.norm(inp-c)


In [27]:
dist_inp_a , dist_inp_b, dist_inp_c

(np.float64(0.7504763757808104),
 np.float64(0.8504144454236802),
 np.float64(1.1830916304539874))