In [3]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-f8fd85b48e1345aff339a73271b309ac30058e036059bf5cdf316ad4cac40c4a"

payload = {
    "input": "my name is ramesh",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})

print(response.json())


{'object': 'list', 'data': [{'object': 'embedding', 'embedding': [0.031655025, -0.039910734, -0.048264142, -0.010270786, -0.030702444, -0.044502668, -0.0060208053, 0.017952502, -0.059743974, -0.06799968, 0.022910813, -0.013617034, -0.01798914, -0.026281487, 0.008982358, -0.015729811, -0.010722651, 0.021262113, 0.00038259744, 0.0422067, 0.033120535, -0.003917187, 0.05456584, 0.0228009, 0.0066436473, 0.036930863, 0.015986277, 0.004100376, 0.041571647, -0.059353173, 0.018099053, -0.023997733, 0.036149256, -0.054468136, 0.015509985, -0.019711114, 0.011040178, -0.03385329, -0.038640626, 0.0038652837, -0.030629167, -0.018355519, 0.070051394, 0.055933647, -0.041034292, -0.009251035, -0.094720826, -0.006411608, 0.059597425, -0.023912245, -0.030042963, 0.03556305, 0.009709006, 0.06658302, 0.022690985, -0.015082545, 0.03895815, 0.036173683, 0.032167953, -0.037028562, -0.00023184833, -0.019271461, 0.008957933, -0.013580397, -0.030848995, 0.06267499, -0.03243663, 0.012243118, -0.009592987, 0.03309

In [4]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [5]:
result = response.json()

In [7]:
result

{'object': 'list',
 'data': [{'object': 'embedding',
   'embedding': [0.031655025,
    -0.039910734,
    -0.048264142,
    -0.010270786,
    -0.030702444,
    -0.044502668,
    -0.0060208053,
    0.017952502,
    -0.059743974,
    -0.06799968,
    0.022910813,
    -0.013617034,
    -0.01798914,
    -0.026281487,
    0.008982358,
    -0.015729811,
    -0.010722651,
    0.021262113,
    0.00038259744,
    0.0422067,
    0.033120535,
    -0.003917187,
    0.05456584,
    0.0228009,
    0.0066436473,
    0.036930863,
    0.015986277,
    0.004100376,
    0.041571647,
    -0.059353173,
    0.018099053,
    -0.023997733,
    0.036149256,
    -0.054468136,
    0.015509985,
    -0.019711114,
    0.011040178,
    -0.03385329,
    -0.038640626,
    0.0038652837,
    -0.030629167,
    -0.018355519,
    0.070051394,
    0.055933647,
    -0.041034292,
    -0.009251035,
    -0.094720826,
    -0.006411608,
    0.059597425,
    -0.023912245,
    -0.030042963,
    0.03556305,
    0.009709006,
    0.066

In [8]:
len(result['data'][0]['embedding'])

1536

In [9]:
a = result['data'][0]['embedding']

In [10]:
a

[0.031655025,
 -0.039910734,
 -0.048264142,
 -0.010270786,
 -0.030702444,
 -0.044502668,
 -0.0060208053,
 0.017952502,
 -0.059743974,
 -0.06799968,
 0.022910813,
 -0.013617034,
 -0.01798914,
 -0.026281487,
 0.008982358,
 -0.015729811,
 -0.010722651,
 0.021262113,
 0.00038259744,
 0.0422067,
 0.033120535,
 -0.003917187,
 0.05456584,
 0.0228009,
 0.0066436473,
 0.036930863,
 0.015986277,
 0.004100376,
 0.041571647,
 -0.059353173,
 0.018099053,
 -0.023997733,
 0.036149256,
 -0.054468136,
 0.015509985,
 -0.019711114,
 0.011040178,
 -0.03385329,
 -0.038640626,
 0.0038652837,
 -0.030629167,
 -0.018355519,
 0.070051394,
 0.055933647,
 -0.041034292,
 -0.009251035,
 -0.094720826,
 -0.006411608,
 0.059597425,
 -0.023912245,
 -0.030042963,
 0.03556305,
 0.009709006,
 0.06658302,
 0.022690985,
 -0.015082545,
 0.03895815,
 0.036173683,
 0.032167953,
 -0.037028562,
 -0.00023184833,
 -0.019271461,
 0.008957933,
 -0.013580397,
 -0.030848995,
 0.06267499,
 -0.03243663,
 0.012243118,
 -0.009592987,
 0.0

In [11]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-f8fd85b48e1345aff339a73271b309ac30058e036059bf5cdf316ad4cac40c4a"

payload = {
    "input": "sudhanshu use to work for euron",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
b = response.json()['data'][0]['embedding']

In [13]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-f8fd85b48e1345aff339a73271b309ac30058e036059bf5cdf316ad4cac40c4a"

payload = {
    "input": "rakesh a gen ai batch student",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
c = response.json()['data'][0]['embedding']


In [14]:
a,b,c

([0.031655025,
  -0.039910734,
  -0.048264142,
  -0.010270786,
  -0.030702444,
  -0.044502668,
  -0.0060208053,
  0.017952502,
  -0.059743974,
  -0.06799968,
  0.022910813,
  -0.013617034,
  -0.01798914,
  -0.026281487,
  0.008982358,
  -0.015729811,
  -0.010722651,
  0.021262113,
  0.00038259744,
  0.0422067,
  0.033120535,
  -0.003917187,
  0.05456584,
  0.0228009,
  0.0066436473,
  0.036930863,
  0.015986277,
  0.004100376,
  0.041571647,
  -0.059353173,
  0.018099053,
  -0.023997733,
  0.036149256,
  -0.054468136,
  0.015509985,
  -0.019711114,
  0.011040178,
  -0.03385329,
  -0.038640626,
  0.0038652837,
  -0.030629167,
  -0.018355519,
  0.070051394,
  0.055933647,
  -0.041034292,
  -0.009251035,
  -0.094720826,
  -0.006411608,
  0.059597425,
  -0.023912245,
  -0.030042963,
  0.03556305,
  0.009709006,
  0.06658302,
  0.022690985,
  -0.015082545,
  0.03895815,
  0.036173683,
  0.032167953,
  -0.037028562,
  -0.00023184833,
  -0.019271461,
  0.008957933,
  -0.013580397,
  -0.030848

In [16]:
import requests

url = "https://api.euron.one/api/v1/euri/embeddings"
token = "euri-f8fd85b48e1345aff339a73271b309ac30058e036059bf5cdf316ad4cac40c4a"

payload = {
    "input": "what sudhanshu does",
    "model": "text-embedding-3-small"
}

response = requests.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
inp = response.json()['data'][0]['embedding']


In [20]:
type(inp)

list

In [17]:
import numpy as np

In [18]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [19]:
type(a)

list

In [21]:
a = np.array(a)
b= np.array(b)
c = np.array(c)
inp = np.array(inp)

In [24]:
a,b,c,inp

(array([-0.00645238, -0.02682346, -0.02852873, ..., -0.00969585,
         0.01474829, -0.00714371], shape=(1536,)),
 array([-0.0461162 , -0.00981342,  0.05917026, ...,  0.00189482,
         0.00919579, -0.01663782], shape=(1536,)),
 array([-0.00416988, -0.03700995,  0.05361585, ..., -0.03120966,
         0.05270311, -0.01773945], shape=(1536,)),
 array([-0.03277422,  0.00336288,  0.05129212, ..., -0.00561822,
        -0.00875308,  0.00986446], shape=(1536,)))

In [22]:
dist_inp_a = np.linalg.norm(inp-a)
dist_inp_b = np.linalg.norm(inp-b)
dist_inp_c = np.linalg.norm(inp-c)


In [23]:
dist_inp_a , dist_inp_b, dist_inp_c

(1.1945655160083541, 0.8503761516216858, 1.1830916304539874)

In [24]:
max(dist_inp_a , dist_inp_b, dist_inp_c)

1.1945655160083541